name: google_maps_flutter_heatmap
description: A Flutter plugin for integrating Google Maps in iOS and Android applications. with heatmap support

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1+3

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemaps
        pluginClass: GoogleMapsPlugin
      ios:
        pluginClass: FLTGoogleMapsPlugin

