name: google_maps_flutter_heatmap
description: A Flutter plugin for integrating Google Maps in iOS and Android applications. with heatmap support

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1+3

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: google_maps_flutter_android
      ios:
        default_package: google_maps_flutter_ios

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_android: ^2.1.10
  google_maps_flutter_ios: ^2.1.10
  google_maps_flutter_platform_interface: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  stream_transform: ^2.0.0